### ISSUE TITLE
Invalid download links

### ISSUE THREAD

**Issue by beluci-dev** [yupswing/TileCraft#9]
you can fix the links please? i cant compile....

**Comment by Wulf** [comment]
Hey @Heronbeluci, I managed to determine which haxe/neko/dependency versions to use in order to get this to compile. See https://github.com/Wulf/TileCraft#dependency-version-matrix

Just want to thank Simone, AngryOctopus, and LostGarden for their direct/indirect effort behind this tool.

**Comment by yupswing** [comment]
I am really sorry I did not update the links.
Compiled version uploaded (in "releases") and images fixed.

Thanks Wulf for your effort to find a way to compile TileCraft today.

**Comment by Wulf** [comment]
Awesome, thanks @yupswing.
